"""
Student information for this assignment:

Replace Vineet Burugu with your name.
On my/our honor, Vineet Burugu and Aarnav Chitari, this 
programming assignment is my own work and I have not provided this code to 
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: vsb433
UT EID 2: ac84787
"""


def length_of_longest_substring_n3(s):
    """
    Finds the length of the longest substring without repeating characters
    using a brute force approach (O(N^3)).

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
            in s that contains no repeating characters.
    """
    n = len(s)
    maxlength = 0
    for i in range(n):
        for j in range(i + 1, n + 1):
            my_substr = s[i:j]

            frequency = [0] * 256

            repeats = False
            for char in my_substr:
                charindex = ord(char)
                frequency[charindex] += 1
                if frequency[charindex] > 1:
                    repeats = True

            if not repeats:
                length = j - i
                maxlength = max(maxlength, length)

    if not s:
        return 0

    return maxlength

def length_of_longest_substring_n2(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N^2)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
        in s that contains no repeating characters.
    """
    n = len(s)
    maxlength = 0

    for i in range(n):
        frequency = [0] * 256
        for j in range(i,n):
            charindex = ord(s[j])
            frequency[charindex] += 1
            repeats = False
            for k in range(256):
                if frequency[k] > 1:
                    repeats = True
            if not repeats:
                length = j - i + 1
                maxlength = max(maxlength, length)
    if not s:
        return 0
    return maxlength


def length_of_longest_substring_n(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list. However, this approach stops early, breaking out of the inner
    loop when a repeating character is found. You may also choose to challenge
    yourself by implementing a sliding window approach.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
        in s that contains no repeating characters.
    """
    n = len(s)
    maxlength = 0

    for i in range(n):
        frequency = [0] * 256
        length = 0

        for j in range(i, n):
            index = ord(s[j])
            if frequency[index]:
                break
            frequency[index] = 1
            length += 1

        maxlength = max(maxlength, length)
    if not s:
        return 0
    return maxlength
